CREATE DATABASE IF NOT EXISTS productiveapp;

USE productiveapp;

CREATE TABLE IF NOT EXISTS users(
	id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL,
    passwd VARCHAR(20) NOT NULL,
    PRIMARY KEY(id)
);